# fly.toml file generated for gobblebot on 2023-03-29T20:39:19+02:00

app = "gobblebot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[build]
  builtin = "node"

[experimental]
  auto_rollback = true

[mounts]
  source="gobblebot_data"
  destination="/data"
